# Generated by Django 5.0.4 on 2024-05-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='card_num',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='expdate',
        ),
        migrations.AlterField(
            model_name='membership',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='cell',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='lname',
            field=models.CharField(max_length=100),
        ),
    ]
