# Generated by Django 5.0.4 on 2024-05-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_membership_card_num_remove_membership_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default=' ', max_length=1000),
        ),
    ]
